<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.name like :chaine')
                    ->orderBy('u.id')
                    ->setParameter('chaine', $chaine);

        return $qb->getQuery()->getResult();
    }
}
